// Intentional layering is declared by semantic construction, not by detected
// collisions. No rule exempts text/text, headings, legends, or whole charts.
export const OVERLAP_POLICY = Object.freeze({
  containedCellMarks: ["table-bullet", "table-binary-mark", "table-rating-track", "table-rating-sector", "table-bar", "table-implication"],
  surfaces: ["divider-surface", "section-surface", "rail-surface", "panel-surface", "insight-surface", "quote-surface", "image-frame", "annotation-surface"],
  containedLabels: {
    "table-cell": "table-cell-text", "table-header-cell": "table-header-text",
    "organization-node": "node-label", "tree-node": "node-label", "tree-root": "node-label", "organization-root": "node-label",
    "insight-tree-insight-surface": "insight-tree-insight-text", "insight-tree-implication-surface": "insight-tree-implication-text",
    "funnel-stage": "funnel-label", "icon-surface": "icon-symbol",
    "logo-backing": "logo-text", "trend-label-surface": "trend-label",
    "process-marker": "process-number", "list-marker": "list-marker-label",
    "quote-avatar": "quote-avatar-label",
    "tracker-marker": "tracker-marker-label", "tracker-compact-marker": "tracker-compact-marker-label",
    "highlight-marker": "highlight-number", "matrix-point": "matrix-point-label",
    "rollout-phase": "rollout-phase-label", "process-band": "process-label",
    "status-marker": "status-cue", "rollout-row-marker": "rollout-row-label",
    "chart-mark": "data-label", "chart-segment": "data-label", "chart-label-surface": "data-label",
    "table-number-circle": "table-number-value", "table-section-marker": "table-section-number"
  },
  chartGeometry: ["chart-gridline", "chart-axis", "chart-threshold-line", "chart-mark", "chart-marker", "chart-line", "chart-area", "chart-reference-line", "chart-connector", "chart-point-highlight", "horizon-axis", "horizon-curve", "horizon-step-line"],
  pairs: [
    ["table-rating-track", "table-rating-sector", "ordinal sector overlays its own neutral disc"],
    ["table-binary-mark", "table-binary-mark", "check or cross stroke junction"],
    ["relationship-disc", "relationship-chevron", "chevron inside its own inference marker"],
    ["relationship-chevron", "relationship-chevron", "inference chevron joint"],
    ["image-placeholder-line", "image-placeholder-line", "placeholder diagonals"],
    ["tree-connector", "tree-connector", "organization branch junctions"],
    ["tree-root", "tree-connector", "tree connector terminates at its own root"],
    ["tree-connector", "tree-node", "tree connector terminates at its own node"],
    ["organization-root", "tree-connector", "organization connector terminates at its own root"],
    ["tree-connector", "organization-node", "organization connector terminates at its own node"],
    ["matrix-axis", "matrix-axis", "matrix origin"],
    ["matrix-axis", "matrix-boundary", "matrix quadrant junction"],
    ["matrix-boundary", "matrix-boundary", "matrix quadrant junction"],
    ["matrix-boundary", "matrix-point", "point at quadrant boundary"],
    ["matrix-highlight", "matrix-boundary", "highlighted quadrant"],
    ["matrix-highlight", "matrix-point-label", "label in highlighted quadrant"],
    ["roadmap-rail", "roadmap-marker", "wave marker on roadmap rail"],
    ["process-rail", "process-marker", "step markers sit on the process rail"],
    ["map-land", "map-marker", "map marker anchored to geography"],
    ["map-land", "map-marker-fill", "map marker anchored to geography"],
    ["map-land", "map-label", "map label anchored to geography"],
    ["map-land", "map-land", "contiguous map land mass"],
    ["map-marker", "map-marker-fill", "fraction overlays its own map marker"],
    ["matrix-highlight", "matrix-point", "point is in the highlighted quadrant"],
    ["chart-segment", "chart-hole", "donut hole masks the segment center"],
    ["chart-segment", "chart-segment", "adjacent segments share one chart origin and boundary"],
    ["chart-mark", "data-label-leader", "external data label leader terminates at its own mark"],
    ["chart-marker", "chart-point-highlight-label", "selected point label"],
    ["chart-point-highlight", "chart-point-highlight-label", "selected point label"],
    ["tracker-rail", "tracker-marker", "tracker marker sits on its sequence rail"],
    ["tracker-compact-rail", "tracker-compact-marker", "compact tracker marker sits on its one stable rail"],
    ["table-cell", "table-section-marker", "centered section marker straddles its category cell"],
    ["table-cell", "table-section-number", "section number sits inside its protruding marker"],
    ["table-header-cell", "table-rule", "table rule sits on its own header boundary"],
    ["annotation-endpoint", "annotation-leader", "dot terminates its own orthogonal evidence leader"],
    ["annotation-endpoint", "chart-marker", "dot is anchored to the exact keyed chart point"],
    ["annotation-endpoint", "chart-line", "dot is anchored to the exact keyed chart point"],
    ["annotation-endpoint", "chart-mark", "dot is anchored to the exact keyed chart mark"],
    ["annotation-endpoint", "chart-point-highlight", "dot is anchored to the exact keyed chart point"]
  ]
});
